export const dataSource = [
  {
    key: "1",
    field1: "value1",
    field2: "value2",
    field3: "value3",
    field4: "value4",
    field5: "value5",
    field6: "value6",
    field7: "value7",
    field8: "value8",
    field9: "value9",
  },
  {
    key: "1",
    field1: "value1",
    field2: "value2",
    field3: "value3",
    field4: "value4",
    field5: "value5",
    field6: "value6",
    field7: "value7",
    field8: "value8",
    field9: "value9",
  },
  {
    key: "1",
    field1: "value1",
    field2: "value2",
    field3: "value3",
    field4: "value4",
    field5: "value5",
    field6: "value6",
    field7: "value7",
    field8: "value8",
    field9: "value9",
  },
  {
    key: "1",
    field1: "value1",
    field2: "value2",
    field3: "value3",
    field4: "value4",
    field5: "value5",
    field6: "value6",
    field7: "value7",
    field8: "value8",
    field9: "value9",
  },
  {
    key: "1",
    field1: "value1",
    field2: "value2",
    field3: "value3",
    field4: "value4",
    field5: "value5",
    field6: "value6",
    field7: "value7",
    field8: "value8",
    field9: "value9",
  },
];

export const columns = [
  {
    title: "field1",
    dataIndex: "field1",
    key: "field1",
    width: "125px",
  },
  {
    title: "field2",
    dataIndex: "field2",
    key: "field2",
    width: "125px",
  },
  {
    title: "field3",
    dataIndex: "field3",
    key: "field3",
    width: "125px",
  },
  {
    title: "field4",
    dataIndex: "field4",
    key: "field4",
    width: "125px",
  },
  {
    title: "field5",
    dataIndex: "field5",
    key: "field5",
    width: "125px",
  },
  {
    title: "field6",
    dataIndex: "field6",
    key: "field6",
    width: "125px",
  },
  {
    title: "field7",
    dataIndex: "field7",
    key: "field7",
    width: "125px",
  },
  {
    title: "field8",
    dataIndex: "field8",
    key: "field8",
    width: "125px",
  },
  {
    title: "field9",
    dataIndex: "field9",
    key: "field9",
    width: "125px",
  },
];
